name: main

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 5"

jobs:

  plugin_test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        ver: [0.3.0]

    runs-on: ${{ matrix.os }}

    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1.0.0
        with:
          version: ${{ matrix.ver }}
          command: cloudwaste --version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
